---
swagger: "2.0"
info:
  version: "2023-11-01T15:32:26Z"
  title: "lambdaTest"
host: "hahd5jtxrk.execute-api.us-east-1.amazonaws.com"
basePath: "/newDev"
schemes:
- "https"
paths:
  /:
    post:
      consumes:
      - "application/json"
      responses:
        "200":
          description: "200 response"
      security:
      - newAuth: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:703543943062:function:TestLambdaFunction/invocations"
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "#set($inputRoot = $input.path('$'))\n{  \"files\": $inputRoot.files,\n\
            \    \"acls\":\"$context.authorizer.acls\"\n}"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
securityDefinitions:
  newAuth:
    type: "apiKey"
    name: "authorization"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
    x-amazon-apigateway-authorizer:
      authorizerUri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:703543943062:function:GatewayCustomAuthorizer/invocations"
      authorizerResultTtlInSeconds: 300
      type: "token"
